(* Turns the standard library's sources into an OCaml module holding them.

   The binary carries its standard library rather than looking for one, so
   that it works from any directory and so that a directory named `stdlib/`
   cannot be mistaken for it. The alternative -- marshalling parsed ASTs --
   ties the artifact to the compiler that wrote it and to our own type
   definitions, which turns every refactor into a format migration. The
   sources are 34 KB and parse in a millisecond or two, and the compile cache
   already covers the repeat cost.

   Values are written with `%S` rather than a `{wand|...|wand}` literal:
   readable output is worth nothing here, and an escaped string cannot be
   broken by a module that happens to contain the delimiter. *)

let () =
  let files =
    Sys.argv
    |> Array.to_list
    |> List.tl
    |> List.filter (fun f -> Filename.check_suffix f ".wand")
    |> List.sort compare
  in
  print_string "(* Generated by tools/gen_stdlib_embed.ml. Do not edit. *)\n\n";
  print_string "let table : (string * string) list =\n  [ ";
  List.iteri
    (fun i f ->
      let name = Filename.remove_extension (Filename.basename f) in
      let src = In_channel.with_open_bin f In_channel.input_all in
      if i > 0 then print_string "  ; ";
      Printf.printf "(%S, %S)\n" name src)
    files;
  print_string "  ]\n"
